server:
  addr: "127.0.0.1"
  port: "80"
  openProxy: true
logSet:
  logFilePath: "./config/log/"
  logFileName: "log.log"
  saveMaxURI: 1024
mysqlMake:
  username: "root"
  password: "root"
  db-name: "xmlt_make"
  path: "127.0.0.1"
  port: "3306"
  autoMigrate: false
mysqlOnline:
  username: "root"
  password: "root"
  db-name: "xmlt_online"
  path: "127.0.0.1"
  port: "3306"
  autoMigrate: false